---
- name: Reconfigure the host name
  lineinfile:
    path: /etc/hosts
    state: absent
    regexpp: "{{ item.ip}}"
  with_items:
    - { ip: "{{ inventory_hostname}}"}
- name: add new hosts
  lineinfile:
    path: /etc/hosts
    state: present
    line: "{{ item.hostname item.ip}}"
  with_items:
    - {hostname: "{{ ansible_hostname }}", ip: "{{ inventory_hostname}}"}

- name: Manage entries in sysctl.conf
  sysctl:
    name: "{{item.name}}"
    value: "{{item.value}}"
    state: present
    reload: yes
  with_items:
    - { name: "{{kernel.shmall}}",value: "{{ansible_memtotal_mb * 1024 * 1024 -1}}"}
    - { name: "{{kernel.shmmax}}",value: "{{ ansible_memtotal_mb * 1024 *1024 -1}}"}
    - { name: "{{kernel.shmmni}}",value: 4096}
    - { name: "kernel.sem" , value: "250 32000 100 240"   }
    - { name: "kernel.randomize_va_space" , value: 0  }
    - { name: "fs.file-max" , value: 6815744  }
    - { name: "fs.aio-max-nr" , value: 1048576  }
    - { name: "net.core.rmem_default" , value: 262144  }
    - { name: "net.core.rmem_max" , value: 4194304  }
    - { name: "net.core.wmem_default" , value: 262144  }
    - { name: "net.core.wmem_max" , value: 1048576  }

- name: disable SELinux
  selinux:
    state: disabled

- name: disable firewalld,avahi-deamon
  systemd: 
    name: "{{item.name}}"
    state: "{{item.state}}"
    enable: "{{item.enable}}"
  with_items:
    - { name: "{{firewalld}}", state: "{{stopped}}",enable: "{{no}}"}


- name: 'set PemoveIPC=no'
  lineinfile:
    path: /etc/systemd/logind.conf
    state: present
    line: "RemoveIPC=no"

- name: "set "
